### ISSUE TITLE
Auto reload translation

### ISSUE THREAD

**Issue by antonmedv** [change/linguist#15]
Is it possible to implement hot reload translations then file changes?

**Comment by chrismccord** [comment]
Are you using Phoenix with live reload? If so, you can add the locales directory/files to your list of live reload patterns in dev.exs

**Comment by antonmedv** [comment]
Yes, i’m using live reload. How to do it? :)

**Comment by chrismccord** [comment]
``` elixir
  live_reload: [
    patterns: [
      ~r{config/locales/.*(exs)$}, # add this
      ~r{priv/static/.*(js|css|png|jpeg|jpg|gif)$},
      ~r{web/views/.*(ex)$},
      ~r{web/templates/.*(eex)$}
    ]
  ]
```

**Comment by antonmedv** [comment]
Yes, browser reloads, but still with old translations.
