### ISSUE TITLE
How to use in the phoenix framework?

### ISSUE THREAD

**Issue by mesosteros** [change/linguist#16]
First off I'm a complete noob to Elixir and Phoenix.
Nevertheless I'm taking this head on.

How can I use this package with Phoenix?
I don't know where in which folder to write the module file as well as if it should be ex or exs in extension like the other language file in the Usage (fr.exs).

After writing that, how exactly would I apply it to my HTML tags?

**Comment by OpakAlex** [comment]
@chrismccord can you answer?

**Comment by chrismccord** [comment]
Add it to your mix deps:

``` elixir
def deps do
  [...,
  {:linguist, "~> 0.1.5"}]
end
```

add a `MyApp.I18n` (i18n.ex) module somewhere in your project, say `web/i18n.ex`. Add your `.exs` locales somewhere in your project, say `config/locales/`

Import the functions into your `web/web.ex` `view` block:

```
import MyApp.I18n
```

use in templates

```
<%= t!("en", "foo.bar.baz") %>
```

**Comment by OpakAlex** [comment]
@chrismccord thanks man!
Maybe you can tell, where i can store current_locale ?)

**Comment by chrismccord** [comment]
You need to place it in a conn assign somewhere in your stack `assign(conn, locale, the_users_locale)`, then you can `<%= t!(@locale, "foo.bar.baz") %>`

**Comment by OpakAlex** [comment]
ok. thanks man!

**Comment by mesosteros** [comment]
Curiously I had just done this again. :)
But I didn't know that info about storing the current locale. Thanks @chrismccord 
Just one thing: I didn't use `import MyApp.I18n` in my `web/web.ex` file or at all. I don't think it is necessary.
